cd /home/nam/mydroid/out/target/product/generic 
echo Deleting system.img from `pwd` ... 
rm system.img 
echo Creating system.img in `pwd`...
/home/nam/mydroid/out/host/linux-x86/bin/mkyaffs2image system system.img
